name: Lint & Test

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 1 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean Install
      run: npm ci

    - name: Run test
      run: npm run test:coverage

    - name: Coverage report
      uses: codecov/codecov-action@v2
      with:
        directory: ./reports/coverage
        flags: unittests

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Send Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ fromJSON('[\":white_check_mark: Workflow was successful\", \":rotating_light: Workflow failed\"]')[job.status == 'success'] }}",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Ref Name*:\n$GITHUB_REF_NAME"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Actor*:\n$GITHUB_ACTOR"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
                  }
                ]
              }
            ]
          }
