name: Lint & Test

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 1 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean Install
      run: npm ci

    - name: Run test
      run: npm run test:coverage

    - name: Coverage report
      uses: codecov/codecov-action@v2
      with:
        directory: ./reports/coverage
        flags: unittests

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Prepare Github event
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Event:\n${{ toJSON(github.event) }}"

        echo "GITHUB_REPO_URL=`echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY`" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Send Slack Notification
      if: always()
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ fromJSON('[":rotating_light: Workflow failed", ":tada: Workflow was successful"]')[job.status == 'success'] }}",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow*:\n${{ github.workflow }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Ref Name*:\n<${{ format('{0}/tree/{1}', env.GITHUB_REPO_URL, github.ref_name) }}|${{ github.ref_name }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Actor*:\n${{ github.actor.login }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*SHA*:\n<${{ format('{0}/commits/{1}', env.GITHUB_REPO_URL, github.sha) }}|${{ env.GITHUB_SHA_SHORT }}>"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${{ format('{0}/actions/runs/{1}', env.GITHUB_REPO_URL, github.run_id) }}"
                  }
                ]
              }
            ]
          }
